apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-2
  labels:
    app: webapp-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-2
  template:
    metadata:
      labels:
        app: webapp-2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
