apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-app2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/example/app-of-app/webapp-2
    repoURL: https://github.com/royjoydeep11/kubernetes.git
    targetRevision: HEAD
